### ISSUE TITLE
Значения параметров

### ISSUE THREAD

**Issue by casa7x** [xydoy92/lesson_16#1]
https://github.com/xydoy92/lesson_16/blob/a17d3288d29a445c07a5318a5b08d8f0397f8caf/changedArrayFunctionTask.js#L4

Лучше запрашивать отдельно и передавать потом как значения. Даже если ты хотел использовать это как дефолтные значения, прямая передача промпта и других функций, не рекомендуется.  Параметры должны быть более чистыми сущностями, а не получать значения в моменте объявления, если только это не дефолтное значение опять таки, а тут оно никак не может быть дефолтным, потому-что всё время разное

**Comment by xydoy92** [comment]
Понял, переделал.
