### ISSUE TITLE
Ввынести массивы

### ISSUE THREAD

**Issue by casa7x** [xydoy92/lesson_16#2]
https://github.com/xydoy92/lesson_16/blob/a17d3288d29a445c07a5318a5b08d8f0397f8caf/massiveAndFunctionsTask.js#L6

Вынеси их в глобальную видимость и спокойно потом переиспользуй, зачем тебе их закрывать на функции.

**Comment by xydoy92** [comment]
Я, конечно, переделал, но это не соответствует ни универсальности функции, ни принципу отсутствия глобальных переменных в функции.
