### ISSUE TITLE
Создать функции

### ISSUE THREAD

**Issue by casa7x** [xydoy92/lesson_16#3]
https://github.com/xydoy92/lesson_16/blob/a17d3288d29a445c07a5318a5b08d8f0397f8caf/massiveAndFunctionsTask.js#L41

Я бы для каждого изменения создал функцию, которая возвращает измененённый массив, чтобы можно было её потом спокойно переиспользовать с другими массивами

**Comment by xydoy92** [comment]
Сделано.
